from typing import Any

__all__ = (
    'scatter_efficiency',
    'scatter_coefficients',
    'scatter_amplitude',
    'scatter_stokes',
    'phase_scatt_HG',
    'scatter_from_phase_function',
    'structure_factor_PY',
    'phase_scatt_ensemble',
    'cross_section_ensemble',
)

def scatter_efficiency(*args: Any, **kwargs: Any) -> Any: ...
def scatter_coefficients(*args: Any, **kwargs: Any) -> Any: ...
def scatter_amplitude(*args: Any, **kwargs: Any) -> Any: ...
def scatter_stokes(*args: Any, **kwargs: Any) -> Any: ...
def phase_scatt_HG(*args: Any, **kwargs: Any) -> Any: ...
def scatter_from_phase_function(*args: Any, **kwargs: Any) -> Any: ...
def structure_factor_PY(*args: Any, **kwargs: Any) -> Any: ...
def phase_scatt_ensemble(*args: Any, **kwargs: Any) -> Any: ...
def cross_section_ensemble(*args: Any, **kwargs: Any) -> Any: ...
