from typing import Any

__all__ = (
    'get_nkfile', 'get_ri_info',
    'lorentz', 'drude', 'tauc_lorentz', 'gaussian', 'multi_oscillator', 'fit_to_oscillator',
    'emt_multilayer_sphere', 'emt_brugg', 'eps_real_kkr',
    'SiO2', 'Silica', 'CaCO3', 'BaSO4', 'BaF2', 'TiO2',
    'BiVO4_mono_a', 'BiVO4_mono_b', 'BiVO4_mono_c', 'BiVO4', 'Cu2O', 'ZnO',
    'MgO', 'Al2O3', 'ZnS', 'GSTa', 'GSTc', 'VO2M', 'VO2R', 'VO2',
    'Si', 'gold', 'silver', 'Cu', 'Al', 'Mg',
    'HDPE', 'PDMS', 'PMMA', 'PVDF', 'H2O',
)

def get_nkfile(*args: Any, **kwargs: Any) -> tuple[Any, Any]: ...
def get_ri_info(*args: Any, **kwargs: Any) -> tuple[Any, Any]: ...
def lorentz(*args: Any, **kwargs: Any) -> Any: ...
def drude(*args: Any, **kwargs: Any) -> Any: ...
def tauc_lorentz(*args: Any, **kwargs: Any) -> Any: ...
def gaussian(*args: Any, **kwargs: Any) -> Any: ...
def multi_oscillator(*args: Any, **kwargs: Any) -> Any: ...
def fit_to_oscillator(*args: Any, **kwargs: Any) -> tuple[Any, Any]: ...
def emt_multilayer_sphere(*args: Any, **kwargs: Any) -> Any: ...
def emt_brugg(*args: Any, **kwargs: Any) -> Any: ...
def eps_real_kkr(*args: Any, **kwargs: Any) -> Any: ...
def SiO2(*args: Any, **kwargs: Any) -> Any: ...
def Silica(*args: Any, **kwargs: Any) -> Any: ...
def CaCO3(*args: Any, **kwargs: Any) -> Any: ...
def BaSO4(*args: Any, **kwargs: Any) -> Any: ...
def BaF2(*args: Any, **kwargs: Any) -> Any: ...
def TiO2(*args: Any, **kwargs: Any) -> Any: ...
def BiVO4_mono_a(*args: Any, **kwargs: Any) -> Any: ...
def BiVO4_mono_b(*args: Any, **kwargs: Any) -> Any: ...
def BiVO4_mono_c(*args: Any, **kwargs: Any) -> Any: ...
def BiVO4(*args: Any, **kwargs: Any) -> Any: ...
def Cu2O(*args: Any, **kwargs: Any) -> Any: ...
def ZnO(*args: Any, **kwargs: Any) -> Any: ...
def MgO(*args: Any, **kwargs: Any) -> Any: ...
def Al2O3(*args: Any, **kwargs: Any) -> Any: ...
def ZnS(*args: Any, **kwargs: Any) -> Any: ...
def GSTa(*args: Any, **kwargs: Any) -> Any: ...
def GSTc(*args: Any, **kwargs: Any) -> Any: ...
def VO2M(*args: Any, **kwargs: Any) -> Any: ...
def VO2R(*args: Any, **kwargs: Any) -> Any: ...
def VO2(*args: Any, **kwargs: Any) -> Any: ...
def Si(*args: Any, **kwargs: Any) -> Any: ...
def gold(*args: Any, **kwargs: Any) -> Any: ...
def silver(*args: Any, **kwargs: Any) -> Any: ...
def Cu(*args: Any, **kwargs: Any) -> Any: ...
def Al(*args: Any, **kwargs: Any) -> Any: ...
def Mg(*args: Any, **kwargs: Any) -> Any: ...
def HDPE(*args: Any, **kwargs: Any) -> Any: ...
def PDMS(*args: Any, **kwargs: Any) -> Any: ...
def PMMA(*args: Any, **kwargs: Any) -> Any: ...
def PVDF(*args: Any, **kwargs: Any) -> Any: ...
def H2O(*args: Any, **kwargs: Any) -> Any: ...
