from typing import Any

__all__ = ('T_beer_lambert', 'adm_sphere', 'adm')

def T_beer_lambert(*args: Any, **kwargs: Any) -> Any: ...
def adm_sphere(*args: Any, **kwargs: Any) -> Any: ...
def adm(*args: Any, **kwargs: Any) -> Any: ...
