from typing import Any

__all__ = (
    'read_spectrafile',
    'AM15',
    'T_atmosphere',
    'T_atmosphere_hemi',
    'Bplanck',
    'yCIE_lum',
    'spectral_average',
    'plot_spectra',
)

def read_spectrafile(*args: Any, **kwargs: Any) -> Any: ...
def AM15(*args: Any, **kwargs: Any) -> Any: ...
def T_atmosphere(*args: Any, **kwargs: Any) -> Any: ...
def T_atmosphere_hemi(*args: Any, **kwargs: Any) -> Any: ...
def Bplanck(*args: Any, **kwargs: Any) -> Any: ...
def yCIE_lum(*args: Any, **kwargs: Any) -> Any: ...
def spectral_average(*args: Any, **kwargs: Any) -> Any: ...
def plot_spectra(*args: Any, **kwargs: Any) -> Any: ...
