from typing import Any

__all__ = ('read_uvvis', 'find_uvvis_samples', 'sample_uvvis')

def read_uvvis(*args: Any, **kwargs: Any) -> Any: ...
def find_uvvis_samples(*args: Any, **kwargs: Any) -> Any: ...
def sample_uvvis(*args: Any, **kwargs: Any) -> Any: ...
